AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS SAM template for deploying a Probot app

Parameters:
  SAMDeploymentRole:
    Type: String
    Description: The ARN of the IAM role that AWS Lambda assumes when it executes your function.
  WebhookSecret:
    Type: String
    Description: The name of the SSM parameter that contains the webhook secret
    Default: /probot/webhook_secret
  AppId:
    Type: String
    Description: GitHub App ID
  GitHubToken:
    Type: String
    Description: GitHub token for authentication


Resources:
  ProbotApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod

  ProbotFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs20.x
      Timeout: 10
      CodeUri: ./
      Role: !Ref SAMDeploymentRole
      Environment:
        Variables:
          NODE_ENV: production
          WEBHOOK_SECRET: !Ref WebhookSecret
          APP_ID: !Ref AppId
          PROBOT_GITHUB_TOKEN: !Ref GitHubToken
      Events:
        HttpPost:
          Type: Api
          Properties:
            Path: /webhook
            Method: post
            RestApiId:
              Ref: ProbotApi

Outputs:
  ProbotFunctionApi:
    Description: 'API Gateway endpoint URL for Probot function'
    Value:
      Fn::Sub: https://${ProbotApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/webhook
