AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS SAM template for deploying a Probot app.🚀

Resources:
  ProbotFunction:
    Type: AWS::Serverless::Function 
    Properties:
      Handler: index.handler
      Runtime: nodejs20.x  
      CodeUri: rupert-the-bot-1.0.0.tgz
      Environment:
        Variables:
          NODE_ENV: production
      Events:
        HttpPost:
          Type: Api
          Properties:
            Path: /webhook
            Method: post

Outputs:
  ProbotFunctionApi:
    Description: "API Gateway endpoint URL for Probot function 🤖"
    Value:
      Fn::Sub: "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/webhook"